### ISSUE TITLE
It doesn't work on Opera GX

### ISSUE THREAD

**Issue by Benfleck102** [newfebriwisnu/WhatsApp-Bypass-Once-View#1]
I installed the extension on my Opera GX, but it didn't work. Do you have any idea how to fix it?

**Comment by newfebriwisnu** [comment]
Hi, currently I just create it for Chrome based, I've tested on chrome and edge. Maybe the next update I'll try to make it. Thank you

**Comment by newfebriwisnu** [comment]
Hi, you can pull the new one, I've fixed and now work on OperaGX
